- name: Pull generated_compress_folder from Google Drive
  import_tasks: "{{ ansible_directory }}/roles/utils/tasks/sub_task.yml"
  vars:
    sub_task_name: "Pull generated_compress_folder from Google Drive({{ generated_folder_name }})"
    tasks_file_path: "{{ ansible_directory }}/roles/drive/tasks/pull.yml"
    filename: "{{ generated_folder_name }}"
    folder_id: "{{ drive_folder_id }}"
    dest: "{{ front_path }}"