version: "3.8"

services:
  shop_back:
    container_name: shop_back
    image: allania7med11/shop_back:latest  # Pulls from Docker Hub
    restart: always
    env_file: ./shop_back/.env
    networks:
      - shop_network

  redis:
    container_name: shop_redis
    image: redis:alpine
    restart: always
    networks:
      - shop_network

  nginx_prod:
    container_name: shop_nginx_prod
    image: allania7med11/shop_nginx_prod:latest  # Pulls from Docker Hub
    restart: always
    ports:
      - "80:80"   # Keep Nginx exposed for HTTP
      - "443:443" # Keep HTTPS access
    networks:
      - shop_network
    depends_on:
      - shop_back

networks:
  shop_network:
    driver: bridge
