- name: Check if PostgreSQL database exists
  shell: "sudo -u postgres psql -lqt | cut -d '|' -f 1 | grep -qw '{{ db_name }}'"
  register: db_exists
  changed_when: false
  check_mode: no

- name: Disconnect clients from PostgreSQL database
  become: yes
  command: >
    sudo -u postgres psql -U {{ postgres_user }} -d postgres -c "SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = '{{ db_name }}' AND pid <> pg_backend_pid();"
  environment:
    PGPASSWORD: "{{ postgres_password }}"
  when: db_exists.rc == 0

- name: Delete PostgreSQL database
  become: yes
  command: >
    sudo -u postgres psql -U {{ postgres_user }} -d postgres -c "DROP DATABASE IF EXISTS {{ db_name }};"
  environment:
    PGPASSWORD: "{{ postgres_password }}"
  when: db_exists.rc == 0
