- name: Ensure correct permissions for /home/vagrant directory
  become: true
  file:
    path: /home/vagrant
    owner: vagrant
    group: vagrant
    mode: "0755"
  ignore_errors: true 

- name: Ensure PostgreSQL database is created if not exists
  command: >
    sudo -u postgres createdb -U {{ postgres_user }} -O {{ postgres_user }} {{ db_name }}
  environment:
    PGPASSWORD: "{{ postgres_password }}"
  ignore_errors: false
  register: create_db_result
  when: not database_exists

