- name: Update apt cache and install dependencies
  ansible.builtin.apt:
    update_cache: yes
    name:
      - libpq-dev
      - gcc
    state: present

- name: Install PostgreSQL and required packages
  ansible.builtin.apt:
    name: 
      - postgresql
      - postgresql-contrib
    state: present

- name: Ensure PostgreSQL service is running
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: yes

- name: Set password for PostgreSQL user
  command: >
    sudo -u postgres psql -c "ALTER USER postgres PASSWORD '{{ postgres_password }}';"


