- name: Template NGINX portfolio configuration
  template:
    src: "../../../templates/portfolio/ngnix.j2"
    dest: /etc/nginx/sites-available/portfolio

- name: Enable NGINX portfolio configuration
  file:
    src: /etc/nginx/sites-available/portfolio
    dest: /etc/nginx/sites-enabled/portfolio
    state: link

- name: Test NGINX configuration
  command: nginx -t
  register: nginx_test
  changed_when: false
  ignore_errors: true

- name: Restart NGINX
  systemd:
    name: nginx
    state: restarted
  when: nginx_test.rc == 0