- name: Exchange refresh_token for access token
  uri:
    url: "https://accounts.google.com/o/oauth2/token"
    method: POST
    body_format: form-urlencoded
    body:
      client_id: "{{ lookup('env', 'CLIENT_ID') }}"
      client_secret: "{{ lookup('env', 'CLIENT_SECRET') }}"
      refresh_token: "{{ lookup('env', 'REFRESH_TOKEN') }}"
      grant_type: "refresh_token"
  register: access_token_response

- name: Set folder_id variable
  set_fact:
    folder_id: "{{ lookup('env', 'FOLDER_ID') }}"
    access_token: "{{ access_token_response.json.access_token }}"
    filename: "portfolio.tgz"

- name: Query files in Google Drive
  uri:
    url: "https://www.googleapis.com/drive/v3/files?q=name%3D'{{ filename }}'+and+'{{ folder_id }}'+in+parents"
    method: GET
    headers:
      Authorization: "Bearer {{ access_token }}"
  register: list_files_response

- name: Extract file IDs
  set_fact:
    file_ids: "{{ list_files_response.json.files | map(attribute='id') | list }}"

- name: Delete files
  uri:
    url: "https://www.googleapis.com/drive/v3/files/{{ item }}"
    method: DELETE
    headers:
      Authorization: "Bearer {{ access_token }}"
    status_code: 204
    validate_certs: yes
  loop: "{{ file_ids }}"
  when: file_ids | length > 0

- name: Upload file to Google Drive
  command: >
    curl --location 'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart' \
    --header 'Authorization: Bearer {{ access_token }}' \
    --form 'metadata={{ metadata | to_json }};type=application/json' \
    --form 'file=@"{{ file_path }}"' \
    -w '%{http_code}' \
    -o /dev/null
  register: curl_output
  vars:
    access_token: "{{ access_token }}"
    metadata: '{"name": "{{ filename }}", "parents": ["{{ folder_id }}"]}'
    file_path: "{{ front_directory }}/{{ filename }}"
  failed_when: curl_output.stdout != "200"