- name: Create new user
  user:
    name: "{{ remote_username }}"
    password: "{{ remote_password | password_hash('sha512') }}"
    createhome: yes

- name: Add user to sudoers
  become: true
  lineinfile:
    dest: /etc/sudoers
    line: "{{ remote_username }} ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'
    state: present

- name: Set Bash as the default shell
  user:
    name: "{{ remote_username }}"
    shell: /bin/bash



- name: Add SSH directory
  file:
    path: "/home/{{ remote_username }}/.ssh"
    state: directory
    owner: "{{ remote_username }}"
    group: "{{ remote_username }}"
    mode: "0700"

- name: Add SSH public key to authorized_keys
  authorized_key:
    user: "{{ remote_username }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"