- name: Set Google Drive access Token
  import_tasks:
    file: "{{ ansible_directory }}/roles/drive/tasks/access_token.yml"

- name: Ngnix configuration
  import_tasks:
    file: "{{ ansible_directory }}/roles/nginx/tasks/config.yml"

- name: Build project
  import_tasks:
    file: "{{ ansible_directory }}/roles/docker/tasks/build.yml"

- name: Push generated_compress_folder and/or env file to Google Drive and Docker image to Dockerhub
  import_tasks:
    file: "{{ ansible_directory }}/roles/docker/tasks/push.yml"