- name: Set full absolute path
  set_fact:
    full_path: "{{ shop_front_path }}"

- name: Extract downloaded file
  become: true
  unarchive:
    src: "{{ full_path }}"
    dest: "/var/www/"
    remote_src: yes
    creates: "/var/www/shop_front"

- name: Set permissions on extracted files
  become: true
  file:
    path: "/var/www/shop_front"
    state: directory
    recurse: yes
    mode: '0755'
