- name: Set full absolute path
  set_fact:
    full_path: "{{ front_path }}"

- name: Extract downloaded file
  become: true
  unarchive:
    src: "{{ full_path }}"
    dest: "/var/www/"
    remote_src: yes

- name: Set permissions on extracted files
  become: true
  file:
    path: "/var/www/shop_front"
    state: directory
    recurse: yes
    mode: '0755'
