version: "3.8"

services:
  shop_back:
    container_name: shop_back
    image: allania7med11/shop_back:latest
    restart: always
    env_file: ./shop_back/.env
    ports:
      - "8000:8000"
    networks:
      - shop_network

  redis:
    container_name: shop_redis
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - shop_network

  nginx_prod:
    container_name: shop_nginx_prod
    image: allania7med11/shop_nginx_prod:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - shop_network
    depends_on:
      - shop_back

networks:
  shop_network:
    driver: bridge
