- name: Execute commands in docker container
  command: docker exec -it {{  project_name }} bash -c 'echo "Hello remote machine"'
  register: result

- name: Print stdout
  debug:
    var: result.stdout