- name: install nginx
  apt: name=nginx state=latest

- name: Unlink default Nginx configuration
  command: unlink /etc/nginx/sites-enabled/default

- name: start nginx
  service:
    name: nginx
    state: started