- name: Build static folder
  import_tasks:
    file: "{{ ansible_directory }}/roles/docker/tasks/build_front.yml"

- name: Convert .env file to dictionary
  import_tasks: 
    file: "{{ ansible_directory }}/roles/env/tasks/convert_env_to_dict.yml"
  vars:
    file_path: "{{ env_file_path }}"
    var_name: "env_dict_run"

- name: Run {{  project_name }} container
  docker_container:
    name: "{{  project_name }}"
    image: "{{  docker_image }}"
    state: started
    restart_policy: always
    networks:
      - name: host
    env:
      "{{ env_dict_run }}"
    detach: yes   # Detach from the container after starting it
