- name: Log into DockerHub
  docker_login:
    username: "{{  dockerhub_username }}"
    password: "{{  dockerhub_password }}"

- name: Pull Docker image from Docker Hub
  docker_image:
    name: "{{  docker_image }}"
    source: pull

- name: Pull generated_compress_folder from Google Drive
  import_tasks: "{{ ansible_directory }}/roles/utils/tasks/sub_task.yml"
  vars:
    sub_task_name: "Pull generated_compress_folder from Google Drive({{ generated_folder_name }})"
    tasks_file_path: "{{ ansible_directory }}/roles/drive/tasks/pull.yml"
    filename: "{{ generated_folder_name }}"
    folder_id: "{{ drive_folder_id }}"
    dest: "{{ back_static_path }}"

- name: Pull env file from Google Drive
  import_tasks: "{{ ansible_directory }}/roles/utils/tasks/sub_task.yml"
  vars:
    sub_task_name: "Pull env file from Google Drive(.env)"
    tasks_file_path: "{{ ansible_directory }}/roles/drive/tasks/pull.yml"
    filename: ".env"
    folder_id: "{{ drive_folder_id }}"
    dest: "{{ env_file_path }}"
