- name: Log into DockerHub
  docker_login:
    username: "{{  dockerhub_username }}"
    password: "{{  dockerhub_password }}"

- name: Push Docker image to Docker Hub
  docker_image:
    name: "{{  docker_image }}"
    push: true
    source: local

- name: Set Google Drive access Token
  import_tasks:
    file: "{{ ansible_directory }}/roles/drive/tasks/access_token.yml"

- name: Push {{ generated_folder_name }} to Google Drive
  import_tasks:
    file: "{{ ansible_directory }}/roles/drive/tasks/push_file.yml"
  vars:
    file_name: "{{ generated_folder_name }}"
    file_path: "{{ generated_compress_folder_path }}"
    folder_id: "{{ drive_folder_id }}"

- name: Push generated_compress_folder to Google Drive
  import_tasks:
    file: "{{ ansible_directory }}/roles/drive/tasks/push_file.yml"
  vars:
    file_name: ".env"
    file_path: "{{ env_file_path }}"
    folder_id: "{{ drive_folder_id }}"
