---
- name: Setup Portfolio
  vars:
    dockerfile_directory: "/vagrant/apps/portfolio/portfolio"
    server: "local.about.effectivewebapp.com"
    backend: "http://localhost:2011"
  hosts: all
  become: true
  roles:
    - portfolio