---
- name: Setup Portfolio
  vars:
    dockerfile_directory: "/vagrant/apps/portfolio/portfolio"
    ansible_directory: "/vagrant/ansible"
    server: false
    listen_port: "2000"
    backend: "http://localhost:2011"
  hosts: all
  become: true
  roles:
    - portfolio