---
- name: Setup Server
  hosts: all
  become: true
  vars:
    current_user: "{{ lookup('env', 'CURRENT_USERNAME') }}"
    remote_username: "{{ lookup('env', 'REMOTE_USERNAME') }}"
    remote_password: "{{ lookup('env', 'REMOTE_PASSWORD') }}"
  roles:
    - user