---
- name: Setup Server
  hosts: "{{ host_on | default('all') }}"
  vars:
    postgres_user: "{{ lookup('env', 'POSTGRES_USER') }}"
    postgres_password: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"
  roles:
    - aptitude
    - postgres
    - docker
    - nginx