---
- name: Create and configure new user
  hosts: prod_root
  gather_facts: no
  become: yes
  vars:
    remote_username: "{{ lookup('env', 'REMOTE_USERNAME') }}"
    remote_password: "{{ lookup('env', 'REMOTE_PASSWORD') }}"
  roles:
    - user