- name: Check if PostgreSQL database exists
  shell: "sudo -u postgres psql -lqt | cut -d '|' -f 1 | grep -qw '{{ db_name }}'"
  register: db_exists
  changed_when: false
  check_mode: no

- name: Ensure PostgreSQL database is created if not exists
  command: >
    sudo -u postgres createdb --owner={{ postgres_user }} {{ db_name }}
  environment:
    PGPASSWORD: "{{ postgres_password }}"
  when: not db_exists.rc == 0

- name: Ngnix configuration
  import_tasks:
    file: "{{ ansible_directory }}/roles/nginx/tasks/config.yml"

- name: Build project
  import_tasks:
    file: "{{ ansible_directory }}/roles/docker/tasks/build_back.yml"
