- name: Set Google Drive access Token
  import_tasks:
    file: "{{ ansible_directory }}/roles/drive/tasks/access_token.yml"

- name: Set database_exists
  import_tasks: "{{ ansible_directory }}/roles/postgres/tasks/check_db.yml" 

- name: Load the database
  import_tasks:
    file: "./load_db.yml"
  when: not database_exists

- name: Ngnix configuration
  import_tasks:
    file: "{{ ansible_directory }}/roles/nginx/tasks/config.yml"

- name: Build project
  import_tasks:
    file: "{{ ansible_directory }}/roles/docker/tasks/build.yml"



