- name: Initiate the database
  import_tasks:
    file: "{{ ansible_directory }}/roles/postgres/tasks/init_db.yml"

- name: Ngnix configuration
  import_tasks:
    file: "{{ ansible_directory }}/roles/nginx/tasks/config.yml"

- name: Build project
  import_tasks:
    file: "{{ ansible_directory }}/roles/docker/tasks/build_back.yml"

- name: Push generated_compress_folder to Google Drive
  import_tasks:
    file: "{{ ansible_directory }}/roles/drive/tasks/push.yml"