echo "****Setup Git****"
SCRIPT_DIR="$(dirname "${BASH_SOURCE[0]}")"
echo "****Load variables from $SCRIPT_DIR/.env****"
source "$SCRIPT_DIR/.env"
git config --global user.name "$GIT_NAME"
git config --global user.email "$GIT_EMAIL"