project_name: "shop_front"
ansible_directory: "{{ lookup('env','PWD') }}/ansible"
repo:  "https://github.com/allania7med11/shop_front"
branch: "main"
project_directory: "/vagrant/apps/shop"
dockerfile_directory: "{{ project_directory }}/shop_front"
env_file_path: "{{ ansible_directory }}/config/{{  project_name }}/.env"
 