project_name: "shop_front"
ansible_directory: "{{ lookup('env','PWD') }}/ansible"
repo:  "https://github.com/allania7med11/shop_front"
branch: "main"
project_directory: "/vagrant/apps/shop"
dockerfile_directory: "{{ project_directory }}/shop_front"
env_file_path: "{{ ansible_directory }}/config/{{  project_name }}/.env"
drive_folder_id: "{{ lookup('env', 'SHOP_FRONT_FOLDER_ID') }}"
generated_folder_name: "{{  project_name }}"
generated_compress_folder_name: "{{  generated_folder_name }}.tgz"
generated_compress_folder_path: "{{ project_directory }}/{{  generated_compress_folder_name }}"
docker_image: "{{ project_name }}"
 